### ISSUE TITLE
How do I use mwdum.py?

### ISSUE THREAD

**Issue by bjarnitor** [andreasnuesslein/mwdum.py#1]
I don't know much about SQL, but I'm intending to import articles from Wikipedia into a local Mediawiki instance.

So I was thinking about doing something like this:

`python mwdum.py enwiki-latest-pages-articles.xml > wikipedia.sql`

And then figure out how to inject the SQL statesments in the file into my mediawiki database.

Is this a right way to do it?

Thanks.

**Comment by axiom17** [comment]
See @mrgloom's response here.
https://github.com/nenadmarkus/pico/issues/4
